### ISSUE TITLE
Pades preparation failed

### ISSUE THREAD

**Issue by zerotohero** [eideasy/nextcloud-electronic-signatures-plugin#58]
I was just trying this plugin for the first time, but something seems to be broken. When I try to sign a PDF, I get this "pades preparation failed" error. Below is the copied error text from the logs, but I don't see anything obvious about what is broken.

{"reqId":"KJu9NW8i0vB4rHGDUytk","level":3,"time":"2021-07-07T15:38:06-04:00","remoteAddr":"172.18.0.3","user":"_user_","app":"electronicsignatures","method":"POST","url":"/apps/electronicsignatures/send_sign_link_by_email","message":"Pades preparation failed.\n#0 /var/www/html/custom_apps/electronicsignatures/lib/Controller/SignApiController.php(147): OCA\\ElectronicSignatures\\Commands\\GetSignLinkLocal->getSignLink('_user_', 'DT_ASUS Boot Se...', 'pdf')\n#1 /var/www/html/custom_apps/electronicsignatures/lib/Controller/SignApiController.php(92): OCA\\ElectronicSignatures\\Controller\\SignApiController->getSignLink('DT_ASUS Boot Se...', 'pdf', '_email_')\n#2 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(217): OCA\\ElectronicSignatures\\Controller\\SignApiController->sendSignLinkByEmail()\n#3 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(126): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\ElectronicSignatures\\Controller\\SignApiController), 'sendSignLinkByE...')\n#4 /var/www/html/lib/private/AppFramework/App.php(156): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\ElectronicSignatures\\Controller\\SignApiController), 'sendSignLinkByE...')\n#5 /var/www/html/lib/private/Route/Router.php(301): OC\\AppFramework\\App::main('OCA\\\\ElectronicS...', 'sendSignLinkByE...', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 /var/www/html/lib/base.php(1000): OC\\Route\\Router->match('/apps/electroni...')\n#7 /var/www/html/index.php(36): OC::handleRequest()\n#8 {main}","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11","id":"60e6040d3958b"}

**Comment by matsjoonas** [comment]
Just to double check, have you entered the correct credentials on the Electronic signatures settings page (/settings/admin/electronicsignatures) ?

**Comment by zerotohero** [comment]
Thanks for the response. Finally got around to looking at this again. I hadn't entered the credentials in the settings page, but now that I have I tried to use the Sandbox mode and I still get an eID error. I created a "worldwide" login, but using the sandbox I don't seem to be able to sign with an email address? Not sure if it's supposed to be working or not.

**Comment by matsjoonas** [comment]
>and I still get an eID error.

What does the error message say?

> using the sandbox I don't seem to be able to sign with an email address?

Could you please share a screenshot of the view where the email signing is missing?
That would help us better understand where the problem occurs since there are email fields in multiple places in the signing flow.

**Comment by matsjoonas** [comment]
Closing due to inactivity.
